jobs:
  validate:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.3
name: Validate Renovate Config
on:
  repository_dispatch:
    types: trigger-ga___renovate-config-validation.yml
